OngPeludo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import index, nosotros, gato, perro, contacto, donar, tablaMascotas, form_mascota, form_mod_mascota, form_del_mascota, form_ver_mascota, verMascota, registro
#Login y logout de Django
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', index, name="index"),
    path('nosotros', nosotros, name="nosotros"),
    path('gato', gato, name="gato"),
    path('perro', perro, name="perro"),
    path('contacto', contacto, name="contacto"),
    path('donar', donar, name="donar"),
    path('tablaMascotas', tablaMascotas, name="tablaMascotas"),
    path('form-mascota', form_mascota, name="form_mascota"),
    path('form-ver-mascota/<id>', form_ver_mascota, name="form_ver_mascota"),
    path('form-mod-mascota/<id>', form_mod_mascota, name="form_mod_mascota"),
    path('form-del-mascota/<id>', form_del_mascota, name="form_del_mascota"),
    path('verMascota/<id>', verMascota, name="verMascota"),
    path('registro', registro, name="registro"),
    path('login', LoginView.as_view(template_name='core/login.html'), name="login"),
    path('logout', LogoutView.as_view(template_name='core/logout.html'), name="logout"),
]

core/models.py
from django.db import models


# Create your models here.

class Especie(models.Model):
    idEspecie = models.IntegerField(primary_key=True, unique=True, verbose_name='Id de especie')
    nombreEspecie =models.CharField(max_length=50, null=False, verbose_name='Nombre Especie')

    def __str__(self):
        return self.nombreEspecie

class Mascota(models.Model):
    chip = models.IntegerField(primary_key=True, blank=False, null=False, verbose_name='N° Chip')
    nombreMascota = models.CharField(max_length=20, null=False, default="", verbose_name='Nombre Mascota')
    especie = models.ForeignKey(Especie, on_delete=models.CASCADE, verbose_name='Especie')
    edad = models.PositiveSmallIntegerField()
    GENEROS = (('Macho', 'Macho'), ('Hembra', 'Hembra'))
    genero = models.CharField(max_length=6, choices=GENEROS, default='M')
    ESTERIL = (('Si', 'Si'), ('No', 'No'))
    esterilizado = models.CharField(max_length=2, choices=ESTERIL, default='S')
    imagen = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.nombreMascota

    #Funcion para eliminar archivo de imagen
    def delete(self, *args, **kwargs):
        self.imagen.delete()
        super().delete(*args, **kwargs)

core/forms.py
from django import forms    
from django.forms import ModelForm
from .models import Mascota
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

#Definimos formulario de registro
class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label='Nombre de Usuario', widget= forms.TextInput(attrs={'placeholder':'Ingrese Nombre de Usuario'}))
    email = forms.EmailField(widget= forms.TextInput(attrs={'placeholder':'usuario@ejemplo.com'}))
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput(attrs={'placeholder':'********'}))
    password2 = forms.CharField(label='Confirma Contraseña', widget=forms.PasswordInput(attrs={'placeholder':'********'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        #Para iterar campos de ayuda y eliminarlos por defecto
        help_texts = {k:"" for k in fields }

#Definimos formulario para mascota
class MascotaForm(ModelForm):

    #Definimos validaciones de caracteres minimos y maximos y placeholders
    chip = forms.CharField(min_length =  5, max_length = 10, label='N° Chip', widget= forms.TextInput(attrs={'placeholder':'Ingrese N° Chip'}))
    nombreMascota = forms.CharField(min_length = 3, max_length=20, label="Nombre Mascota", widget= forms.TextInput(attrs={'placeholder':'Ingrese Nombre'}))
    edad = forms.IntegerField(min_value = 1, max_value = 20, label="Edad", widget= forms.NumberInput(attrs={'placeholder':'Ingrese Edad'}))

    class Meta:
        model = Mascota
        fields = ['chip','nombreMascota','especie','edad','genero','esterilizado','imagen']

    #Definimos un placeholder para el campo de especie
    def __init__(self, *args, **kwargs): 
        super(MascotaForm, self).__init__(*args, **kwargs) 
        self.fields['especie'].empty_label = "Seleccione una Especie"
        

core/views.py
from django.http import request
from core.forms import MascotaForm
from django.shortcuts import render, redirect
from .models import Mascota
from .forms import UserRegisterForm
from django.contrib import messages

# Create your views here.

#funcion para mostrar paginas

def index(request):
    return render(request, 'core/index.html')

def nosotros(request):
    return render(request, 'core/nosotros.html')

def gato(request):
    mascotas = Mascota.objects.filter(especie=1) #Definimos que la especie 1 (gato) se muestre aquí

    datos = {
        'mascotas': mascotas
    }

    #Cuando no hayan mascotas disponibles
    if not Mascota.objects.filter(especie=1).exists():
        datos['mensaje'] = 1

    return render(request, 'core/gato.html', datos)

def perro(request):
    mascotas = Mascota.objects.filter(especie=2) #Definimos que la especie 2 (perro) se muestre aquí


    datos = {
        'mascotas': mascotas
    }

    #Cuando no hayan mascotas disponibles
    if not Mascota.objects.filter(especie=2).exists():
        datos['mensaje'] = 1

    return render(request, 'core/perro.html', datos)

def verMascota(request,id):

    mascota = Mascota.objects.get(chip = id)

    datos = {
        'mascota': mascota
    }

    return render(request, 'core/verMascota.html', datos)

def contacto(request):
    return render(request, 'core/contacto.html')

def donar(request):
    return render(request, 'core/donar.html')

def tablaMascotas(request):

    mascotas = Mascota.objects.all()

    datos = {
        'mascotas': mascotas
    }

    return render(request, 'core/tablaMascotas.html', datos)


def form_mascota(request):

    datos = {
        'form': MascotaForm()
    }

    if request.method == 'POST':
        formulario = MascotaForm(request.POST, files=request.FILES)


        if formulario.is_valid():
            formulario.save()

            datos['mensaje'] = 1
        else:
            datos['mensaje'] = 2


    return render(request, 'core/form_mascota.html', datos)


def form_ver_mascota(request,id):

    mascota = Mascota.objects.get(chip = id)

    datos = {
        'mascota': mascota
    }


    return render(request, 'core/form_ver_mascota.html', datos)



def form_mod_mascota(request,id):

    mascota = Mascota.objects.get(chip = id)

    datos = {
        'form': MascotaForm(instance = mascota)
    }

    if request.method == 'POST':
        formulario = MascotaForm(data = request.POST, instance = mascota, files=request.FILES)


        if formulario.is_valid():
            formulario.save()

            datos['mensaje'] = 1
        else:
            datos['mensaje'] = 2
        datos['form'] = MascotaForm(instance=Mascota.objects.get(chip = id))

    return render(request, 'core/form_mod_mascota.html', datos)

def form_del_mascota(request,id):

    mascota = Mascota.objects.get(chip = id)

    mascota.delete()

    return redirect(to = 'tablaMascotas')


def registro(request):
    #Registrar usuario
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f'Usuario {username} creado')
            return redirect(to = 'index')
    else:
        form = UserRegisterForm()
    context = { 'form' : form }


    return render(request, 'core/registro.html', context)

core/templates/core/form_mascota.html
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Mascota</title>
    <link rel="stylesheet" href="{% static 'core/css/estilos.css'%}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>


<body id="body">
    <div class="jumbotron jumbotron-fluid m-0 py-2" id="jumbotron">
        <div class="container">
            <h1 class="display-4">🐾AYUDA A UN PELUDO🐱</h1>
            <p class="lead">¿Buscas un nuevo mejor amigo? Somos una organización sin fines de lucro protectora de
                animales, que surge de
                la
                necesidad de proteger a animales domésticos en situación de maltrato o abandono, y busca desarrollar una
                cultura
                de protección activa de la vida animal y tenencia responsable de mascotas en nuestro país.</p>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info" id="nav">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">🏠 Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'nosotros' %}">Nosotros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'gato' %}">Gatos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'perro' %}">Perros</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'tablaMascotas' %}">Administrar Mascotas</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contacto' %}">Contacto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'donar' %}">Donar</a>
                    </li>
                    
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">¡Bienvenido
                            {{user.username}}!</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
                    </li>
                    {% else %}
                    <li>
                        <a class="nav-link" href="{% url 'login' %}">Iniciar Sesión</a>
                    </li>
                    <li>
                        <div class="btn-nav">
                            <a class="btn btn-outline-light" href="{% url 'registro' %}">Registrarse</a>
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container my-3">

        <div class="row">
            <div class="col-sm col-md-6">
                <h1>Agregar Mascota</h1>
                <form method="post" action="" id="formulario" enctype="multipart/form-data">
                    {%csrf_token %}
                    <div class="form-group">
                        {{form.as_table}}
                    </div>

                    <input type="submit" class="btn btn-danger mr-2" id="enviar" value="Enviar">
                    <input type="reset" class="btn btn-primary" id="limpiar" value="Limpiar">

                </form>

                {% if mensaje == 1 %}
                <div id="success" class="alert alert-success mt-3" role="alert">
                    Datos ingresados correctamente.
                </div>
                {% elif mensaje == 2 %}
                <div id="error" class="alert alert-danger mt-3" role="alert">
                    Error al ingresar datos.
                </div>
                {% endif %}
            </div>


            <div class="col-sm col-md-6" style="text-align: end;">
                <a href="{% url 'tablaMascotas' %}" class="btn btn-info my-2" role="button">Volver</a>
            </div>

        </div>

    </div>
    <footer class="container-fluid text-white bg-info py-3" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-md">
                    <p>Redes Sociales:</p>
                    <a href="mailto:ayudaaunpeludo@gmail.com">✉️Correo Electrónico</a>
                    <br>
                    <a href="https://www.facebook.com/AyudaAUnPeludo_">👨‍💻Facebook</a>
                    <br>
                    <a href="https://www.instagram.com/AyudaAUnPeludo_">📷Instagram</a>
                    <br>
                    <p class="mt-2">2021 © Todos los Derechos Reservados</p>
                </div>
                <div class="col-md botonNocturno">
                    <button type="button" id="black" class="btn btn-dark">🌛Apagar luces</button>
                    <button type="button" id="white" class="btn btn-light d-none">☀Prender luces</button>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('.form-group input, select').addClass('form-control mb-2');
            $('#id_imagen').removeClass('form-control');
            $('#id_imagen').addClass('form-control-file');

            $('#black').click(function () {
                $('#nav').addClass('bg-dark');
                $('#body').attr('style', 'background-color: #4B4B4B !important');
                $('#jumbotron').attr('style', 'background-color: #4B4B4B !important');
                $('#footer').addClass('bg-dark');
                $('#jumbotron').removeClass('text-dark');
                $('#jumbotron').addClass('text-white');
                $('#body').removeClass('text-dark');
                $('#body').addClass('text-white');
                $('#footer a').removeClass('text-dark');
                $('#footer a').addClass('text-white');
                $('#black').addClass('d-none');
                $('#white').removeClass('d-none');
            })
            $('#white').click(function () {
                $('#nav').removeClass('bg-dark');
                $('#nav').addClass('bg-info');
                $('#body').attr('style', 'background-color: #C2F3F5 !important');
                $('#jumbotron').attr('style', 'background-color: #C2F3F5 !important');
                $('#footer').removeClass('bg-dark');
                $('#footer').addClass('bg-info');
                $('#jumbotron').removeClass('text-white');
                $('#jumbotron').addClass('text-dark');
                $('#body').removeClass('text-white');
                $('#body').addClass('text-dark');
                $('#footer a').removeClass('text-white');
                $('#footer a').addClass('text-dark');
                $('#white').addClass('d-none');
                $('#black').removeClass('d-none');
            })

        })
    </script>

</body>

</html>

core/templates/core/form_mod_mascota.html
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modificar Mascota</title>
    <link rel="stylesheet" href="{% static 'core/css/estilos.css'%}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>

<body id="body">
    <div class="jumbotron jumbotron-fluid m-0 py-2" id="jumbotron">
        <div class="container">
            <h1 class="display-4">🐾AYUDA A UN PELUDO🐱</h1>
            <p class="lead">¿Buscas un nuevo mejor amigo? Somos una organización sin fines de lucro protectora de
                animales, que surge de
                la
                necesidad de proteger a animales domésticos en situación de maltrato o abandono, y busca desarrollar una
                cultura
                de protección activa de la vida animal y tenencia responsable de mascotas en nuestro país.</p>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info" id="nav">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">🏠 Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'nosotros' %}">Nosotros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'gato' %}">Gatos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'perro' %}">Perros</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'tablaMascotas' %}">Administrar Mascotas</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contacto' %}">Contacto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'donar' %}">Donar</a>
                    </li>
                    
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">¡Bienvenido
                            {{user.username}}!</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
                    </li>
                    {% else %}
                    <li>
                        <a class="nav-link" href="{% url 'login' %}">Iniciar Sesión</a>
                    </li>
                    <li>
                        <div class="btn-nav">
                            <a class="btn btn-outline-light" href="{% url 'registro' %}">Registrarse</a>
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container my-3">

        <div class="row">
            <div class="col-sm col-md-6">
                <h1>Modificar Mascota</h1>
                <form method="post" action="" id="formulario" enctype="multipart/form-data">
                    {%csrf_token %}
                    <div class="form-group">
                        {{form.as_table}}
                    </div>

                    <input type="submit" class="btn btn-danger mr-2" id="enviar" value="Modificar">
                    <input type="reset" class="btn btn-primary" id="limpiar" value="Limpiar">

                    
                </form>
                
                {% if mensaje == 1 %}
                    <div id="success" class="alert alert-success mt-2" role="alert">
                        Datos modificados correctamente.
                    </div>
                {% elif mensaje == 2 %}
                    <div id="error" class="alert alert-danger mt-2" role="alert">
                        Error al modificar datos.
                    </div>
                {% endif %}

            </div>


            <div class="col-sm col-md-6" style="text-align: end;">
                <a href="{% url 'tablaMascotas' %}" class="btn btn-info my-2" role="button">Volver</a>
            </div>

        </div>

    </div>
    <footer class="container-fluid text-white bg-info py-3" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-md">
                    <p>Redes Sociales:</p>
                    <a href="mailto:ayudaaunpeludo@gmail.com">✉️Correo Electrónico</a>
                    <br>
                    <a href="https://www.facebook.com/AyudaAUnPeludo_">👨‍💻Facebook</a>
                    <br>
                    <a href="https://www.instagram.com/AyudaAUnPeludo_">📷Instagram</a>
                    <br>
                    <p class="mt-2">2021 © Todos los Derechos Reservados</p>
                </div>
                <div class="col-md botonNocturno">
                    <button type="button" id="black" class="btn btn-dark">🌛Apagar luces</button>
                    <button type="button" id="white" class="btn btn-light d-none">☀Prender luces</button>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('.form-group input, select').addClass('form-control mb-2');
            $('#id_chip').attr('readonly', true);
            $('#id_imagen, #imagen-clear_id').removeClass('form-control');
            $('#id_imagen').addClass('form-control-file');

            $('#black').click(function () {
				$('#nav').addClass('bg-dark');
				$('#body').attr('style', 'background-color: #4B4B4B !important');
				$('#jumbotron').attr('style', 'background-color: #4B4B4B !important');
				$('#footer').addClass('bg-dark');
				$('#jumbotron').removeClass('text-dark');
				$('#jumbotron').addClass('text-white');
				$('#body').removeClass('text-dark');
				$('#body').addClass('text-white');
				$('#footer a').removeClass('text-dark');
				$('#footer a').addClass('text-white');
				$('#black').addClass('d-none');
				$('#white').removeClass('d-none');
			})
			$('#white').click(function () {
				$('#nav').removeClass('bg-dark');
				$('#nav').addClass('bg-info');
				$('#body').attr('style', 'background-color: #C2F3F5 !important');
				$('#jumbotron').attr('style', 'background-color: #C2F3F5 !important');
				$('#footer').removeClass('bg-dark');
				$('#footer').addClass('bg-info');
				$('#jumbotron').removeClass('text-white');
				$('#jumbotron').addClass('text-dark');
				$('#body').removeClass('text-white');
				$('#body').addClass('text-dark');
				$('#footer a').removeClass('text-white');
				$('#footer a').addClass('text-dark');
				$('#white').addClass('d-none');
				$('#black').removeClass('d-none');
			})

        })
    </script>
</body>

</html>